name: Release

on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
    paths:
      - '**/*.tf'
      - '.github/workflows/release.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    uses: XNXKTech/workflows/.github/workflows/release.yml@main
    secrets:
      CI_PAT: ${{ secrets.CI_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
